// Chance Atlas · catalog entries
// Each entry: statistical form, assays affected, effect on the reported result, diagnostic, mitigation, references.
// Mathematics in `form` uses HTML sub/sup so it copies as text. Full derivations live in MATH.md / methods.html.

export const SECTIONS = [
  { id: 'A', name: 'Sampling and partitioning', blurb: 'Molecules, cells and virions come in whole numbers. At low copy number, Poisson and binomial sampling set limits no instrument removes.' },
  { id: 'B', name: 'Amplification', blurb: 'Every copying step is a branching process. Early luck is multiplied exponentially.' },
  { id: 'C', name: 'Detection physics', blurb: 'Photons, electrons and single molecules arrive one at a time.' },
  { id: 'D', name: 'Single-cell biology', blurb: 'Genetically identical cells differ in state, and the state persists long enough to be mistaken for a trait.' },
  { id: 'E', name: 'Population history', blurb: 'Mutation, drift and bottlenecks write randomness into a culture before the assay starts.' },
  { id: 'F', name: 'Apparent stochasticity', blurb: 'Variation that is deterministic in a variable the assay did not record.' },
  { id: 'G', name: 'Worked case: spheroid penetration', blurb: 'An indirect immunofluorescence titration whose curve rises and then falls, decomposed by mechanism.' },
];

export const ENTRIES = [
  /* ------------------------------------------------------------------ A */
  {
    id: 'poisson-partitions', section: 'A', title: 'Poisson loading of partitions', calc: 'poisson',
    one: 'Occupied wells, droplets or beads hide multiple occupancy, and selecting by signal enriches for it.',
    form: 'Units per partition ~ Poisson(λ); λ = −ln <i>f</i><sub>0</sub> from the empty fraction. P(≥2 | occupied) = 1 − λe<sup>−λ</sup>/(1 − e<sup>−λ</sup>). A screen passing each unit with probability φ selects partitions in proportion to 1 − (1 − φ)<sup><i>k</i></sup>, which tends to size-biased sampling as φ → 0, where P(1 | selected) → e<sup>−λ</sup>.',
    assays: ['Limiting-dilution cloning', 'Digital PCR', 'Digital ELISA', 'Single-cell encapsulation', 'Bead loading'],
    effect: 'Precision is best at intermediate occupancy and collapses near saturation. Multi-occupancy is invisible inside a positive partition. Any selection on signal favors partitions with more units: at low density the multi-founder risk of a selected well is twice that of a random occupied well.',
    diagnostic: 'Overdispersion of counts across partitions relative to Poisson (clumping index 2<i>n</i><sub>0</sub><i>n</i><sub>2</sub>/<i>n</i><sub>1</sub><sup>2</sup> above 1) reveals aggregates or volume variation. Compare the selected-sample probability with the plate-level figure.',
    mitigation: 'Dilute to the regime the readout needs, image partitions at time zero, and condition the reported probability on the selection step that produced the sample.',
    refs: [
      { t: 'Coller HA, Coller BS. Hybridoma 1983;2:91–96.', u: 'https://doi.org/10.1089/hyb.1983.2.91' },
      { t: 'Staszewski R. Yale J Biol Med 1984;57:865–868.', u: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC2589791/' },
      { t: 'Hindson BJ, et al. Anal Chem 2011;83:8604–8610.', u: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3216358/' },
      { t: 'Rissin DM, et al. Nat Biotechnol 2010;28:595–599.', u: 'https://pubmed.ncbi.nlm.nih.gov/20495550/' },
      { t: 'Patil GP, Rao CR. Biometrics 1978;34:179–189.', u: 'https://doi.org/10.2307/2530008' },
    ],
    tool: { name: 'Clonality Check (No. 07)', url: 'https://datarichinsightpoor.github.io/clonality-check/' },
  },
  {
    id: 'moi', section: 'A', title: 'Multiplicity of infection and transduction', calc: 'moi',
    one: 'A transduced population is a mixture of copy numbers, and cells that score in a screen carry more copies than average.',
    form: 'Functional copies per cell ~ Poisson(λ), λ = <i>m</i>·<i>f</i><sub>inf</sub>, with <i>m</i> particles per cell and <i>f</i><sub>inf</sub> the infectious fraction. Among transduced cells, P(≥2) = (1 − e<sup>−λ</sup> − λe<sup>−λ</sup>)/(1 − e<sup>−λ</sup>). If each copy independently produces a scoring phenotype with probability φ, cells that score are drawn with weight 1 − (1 − φ)<sup><i>k</i></sup>, so the mean copy number among hits exceeds the mean among transduced cells.',
    assays: ['Pooled CRISPR and shRNA screens', 'Lentiviral transduction', 'Viral infection assays', 'Reporter transfection'],
    effect: 'At λ = 1 roughly 37 percent of cells receive nothing and 26 percent receive two or more. In pooled screens, multiple integrations couple the phenotypes of unrelated guides, and hits are enriched for multi-copy cells. The MOI by particle count and by function differ by the infectious fraction, which is seldom measured.',
    diagnostic: 'Fit the fraction of untransduced cells to e<sup>−λ</sup> to obtain the functional λ. Sequence guide pairs in single cells, or compare hit rates at two MOIs.',
    mitigation: 'Transduce at λ ≈ 0.3, verify the untransduced fraction, and model the copy-number mixture when calling hits.',
    refs: [
      { t: 'Hart T, et al. Cell 2015;163:1515–1526.', u: 'http://sites.utoronto.ca/sidhulab/pdf/Hart_2015_free.pdf' },
      { t: 'Dulbecco R, Vogt M. J Exp Med 1954;99:167–182.', u: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC2180341/' },
    ],
  },
  {
    id: 'endpoint-titration', section: 'A', title: 'Endpoint-dilution titration', calc: 'karber',
    one: 'Interpolated 50 percent endpoints carry sampling error set by wells per dilution and the dilution step.',
    form: 'Wells positive at dilution <i>i</i> ~ Binomial(<i>n</i>, <i>p</i><sub><i>i</i></sub>), <i>p</i><sub><i>i</i></sub> = 1 − e<sup>−dose<sub><i>i</i></sub></sup>. Spearman–Kärber variance of the log<sub>10</sub> titer: (log<sub>10</sub> <i>d</i>)<sup>2</sup> Σ <i>p</i><sub><i>i</i></sub>(1 − <i>p</i><sub><i>i</i></sub>)/(<i>n</i> − 1), with <i>d</i> the dilution factor.',
    assays: ['TCID50', 'Plaque assays', 'LD50 and ID50', 'Most-probable-number counts'],
    effect: 'With eight wells per tenfold step the 95 percent interval spans roughly a factor of 2.6 in each direction. Reed–Muench carries no likelihood and no interval. Two titers that differ by threefold are usually indistinguishable in a single run.',
    diagnostic: 'Report the Kärber or maximum-likelihood interval, and check that the transition spans at least two dilutions.',
    mitigation: 'Use smaller dilution steps across the transition region, more wells per step, and a single-hit likelihood fit.',
    refs: [
      { t: 'Reed LJ, Muench H. Am J Hyg 1938;27:493–497.', u: 'https://doi.org/10.1093/oxfordjournals.aje.a118408' },
      { t: 'Ramakrishnan MA. World J Virol 2016;5:85–86.', u: 'https://www.wjgnet.com/2220-3249/abstract/v5/i2/85.htm' },
    ],
  },
  {
    id: 'low-copy', section: 'A', title: 'Low-copy detection limits', calc: 'lowcopy',
    one: 'Three copies per reaction is the detection floor beneath any chemistry.',
    form: 'Copies in the reaction ~ Poisson(<i>c</i>), <i>c</i> = concentration × volume × extraction efficiency. P(detect) ≤ 1 − e<sup>−<i>c</i></sup>. The 95 percent limit of detection is at least −ln 0.05 ≈ 3.0 copies.',
    assays: ['qPCR and RT-qPCR', 'Rare-variant detection', 'Minimal residual disease', 'Pathogen detection', 'Low-input sequencing'],
    effect: 'At a mean of three copies, 5 percent of reactions contain none. Replicate Ct values widen at low input for sampling reasons before amplification adds its own noise, and a negative replicate at low input is expected, not a failure.',
    diagnostic: 'Plot the detection fraction against nominal copies and compare to 1 − e<sup>−<i>c</i></sup>; a shortfall measures extraction and amplification loss.',
    mitigation: 'Increase template volume or replicate number; define the LoD by probit on replicate detection, as the qPCR guidelines recommend.',
    refs: [
      { t: 'Forootan A, et al. Biomol Detect Quantif 2017;12:1–6.', u: 'https://pubmed.ncbi.nlm.nih.gov/28702366/' },
    ],
  },
  {
    id: 'counting', section: 'A', title: 'Cell seeding and event counting', calc: 'counting',
    one: 'A gate with 50 events carries a 14 percent coefficient of variation before any biology.',
    form: 'Counts ~ Poisson(<i>N</i>); CV = 1/√<i>N</i>. Seeding adds overdispersion from clumping and settling, so wells per plate follow a negative binomial rather than Poisson.',
    assays: ['Viability and proliferation plates', 'Colony-forming assays', 'Flow cytometry of rare populations', 'Hemocytometer counts'],
    effect: 'Starting-count variation propagates directly into fold-growth readouts. Rare-event frequencies from flow gates are Poisson-limited, so a 0.1 percent population counted from 50,000 events (50 events) cannot be distinguished from 0.07 or 0.13 percent.',
    diagnostic: 'Compare the between-well variance of a time-zero readout with its Poisson expectation.',
    mitigation: 'Count enough events for the target CV (1/CV<sup>2</sup>), seed from a well-mixed suspension, and normalize to a time-zero plate.',
    refs: [
      { t: 'Poisson counting statistics are standard; see the Clopper–Pearson interval for the binomial case. Clopper CJ, Pearson ES. Biometrika 1934;26:404–413.', u: 'https://doi.org/10.1093/biomet/26.4.404' },
    ],
  },
  {
    id: 'bottlenecks', section: 'A', title: 'Library representation and bottlenecks', calc: 'bottleneck',
    one: 'Every passage, transduction and PCR resamples the library, and the variance looks like phenotype.',
    form: 'Counts of each element are resampled at each bottleneck, approximately Poisson around the current count at coverage <i>c</i> cells per element. After <i>k</i> neutral bottlenecks the CV of a count is about √(<i>k</i>/<i>c</i>), and the chance of losing an element at one stage is e<sup>−<i>c</i></sup>.',
    assays: ['Pooled CRISPR, shRNA and ORF screens', 'Phage, yeast and mRNA display', 'DNA-encoded libraries', 'Barcoded lineage tracing'],
    effect: 'Guides lost by sampling read as depleted. Selection rounds amplify early random winners (jackpotting), so enrichment ranks partly record who was lucky in round one. At 50-fold coverage across three bottlenecks, the neutral CV is about 24 percent, enough to produce apparent twofold changes by chance.',
    diagnostic: 'Non-targeting controls give the null distribution of fold changes; their spread is the bottleneck variance. Compare replicate screens started from independent transductions.',
    mitigation: 'Maintain coverage above a few hundred cells per element at every step, including PCR input, and start biological replicates before the first bottleneck.',
    refs: [
      { t: 'Hart T, et al. Cell 2015;163:1515–1526.', u: 'http://sites.utoronto.ca/sidhulab/pdf/Hart_2015_free.pdf' },
    ],
  },
  {
    id: 'undersampling', section: 'A', title: 'Sequencing and mass spectrometry undersampling', calc: 'undersampling',
    one: 'Missing values concentrate in low-abundance species, so they are not missing at random.',
    form: 'Reads per molecule ~ Poisson(<i>m</i>); a molecule is seen with probability 1 − e<sup>−<i>m</i></sup> (Lander–Waterman). A clonotype of frequency <i>f</i> is seen in <i>n</i> reads with probability 1 − (1 − <i>f</i>)<sup><i>n</i></sup>. In data-dependent proteomics, precursor selection acts as a stochastic sample of eluting peptides.',
    assays: ['RNA-seq', 'Amplicon and barcode counting', 'Immune repertoire sequencing', 'Shotgun proteomics'],
    effect: 'Fold changes are biased when low-abundance species are imputed or dropped. Repertoire diversity estimators are dominated by the unseen tail. In one shotgun run more than 100,000 peptide features eluted, of which about 16 percent were targeted for fragmentation.',
    diagnostic: 'Rarefaction curves; the fraction of singletons; technical replicate overlap as a function of abundance.',
    mitigation: 'Sequence to saturation for the abundance range that matters, use data-independent acquisition, and model detection probability explicitly.',
    refs: [
      { t: 'Lander ES, Waterman MS. Genomics 1988;2:231–239.', u: 'https://cseweb.ucsd.edu/classes/fa05/cse182/slides/landerwaterman.pdf' },
      { t: 'Michalski A, Cox J, Mann M. J Proteome Res 2011;10:1785–1793.', u: 'https://pubmed.ncbi.nlm.nih.gov/21309581/' },
      { t: 'Laydon DJ, Bangham CRM, Asquith B. Philos Trans R Soc B 2015;370:20140291.', u: 'https://pubmed.ncbi.nlm.nih.gov/26150657/' },
    ],
  },
  /* ------------------------------------------------------------------ B */
  {
    id: 'pcr-branching', section: 'B', title: 'PCR as a branching process', calc: 'pcr',
    one: 'Each template is copied with probability equal to the cycle efficiency, so early-cycle luck is multiplied exponentially.',
    form: 'Galton–Watson process with offspring 2 (probability <i>e</i>) or 1 (probability 1 − <i>e</i>). Mean after <i>n</i> cycles (1 + <i>e</i>)<sup><i>n</i></sup>; CV<sup>2</sup> of the yield from one template (1 − <i>e</i>)/(1 + <i>e</i>) · (1 − (1 + <i>e</i>)<sup>−<i>n</i></sup>); from <i>N</i><sub>0</sub> templates the CV<sup>2</sup> divides by <i>N</i><sub>0</sub>. With <i>U</i> possible molecular identifiers and <i>N</i> molecules, the expected number of distinct labels is <i>U</i>(1 − e<sup>−<i>N</i>/<i>U</i></sup>).',
    assays: ['qPCR at low input', 'Single-cell PCR', 'Amplicon sequencing', 'Library preparation'],
    effect: 'Relative abundances drift from their input proportions, most for the rarest templates. At 90 percent efficiency a single template yields a product with a 23 percent CV even before polymerase error and template switching. Bias, stochasticity, template switching and polymerase error are distinct distortions with different remedies.',
    diagnostic: 'Replicate libraries from split input; the between-replicate CV at each abundance; UMI family-size distributions.',
    mitigation: 'Count molecules with unique molecular identifiers, keep input above the stochastic regime, and minimize cycles.',
    refs: [
      { t: 'Kebschull JM, Zador AM. Nucleic Acids Res 2015;43:e143.', u: 'https://pubmed.ncbi.nlm.nih.gov/26187991/' },
      { t: 'Islam S, et al. Nat Methods 2014;11:163–166.', u: 'https://pubmed.ncbi.nlm.nih.gov/24363023/' },
      { t: 'Bustin S, et al. Clin Chem 2015;61:202–212.', u: 'https://academic.oup.com/clinchem/article-abstract/61/1/202/5611431' },
    ],
  },
  {
    id: 'allele-dropout', section: 'B', title: 'Allele dropout and preferential amplification', calc: 'ado',
    one: 'With two templates, losing one is common, and the heterozygote becomes a homozygote.',
    form: 'Each allele is captured and amplified with probability <i>q</i>. Among samples that amplify at all, P(dropout) = 2<i>q</i>(1 − <i>q</i>)/(1 − (1 − <i>q</i>)<sup>2</sup>).',
    assays: ['Single-cell genotyping', 'Preimplantation genetic testing', 'Low-input forensic and clinical genotyping'],
    effect: 'At <i>q</i> = 0.8, a third of amplified single cells show only one allele. Preferential amplification of shorter fragments adds a directional bias.',
    diagnostic: 'Genotype known heterozygous single cells; the apparent homozygote rate is the dropout rate.',
    mitigation: 'Raise capture efficiency, use multiple displacement or linked markers, and call genotypes with a dropout-aware likelihood.',
    refs: [
      { t: 'Walsh PS, Erlich HA, Higuchi R. PCR Methods Appl 1992;1:241–250.', u: 'https://pubmed.ncbi.nlm.nih.gov/1477658/' },
    ],
  },
  {
    id: 'capture-dropout', section: 'B', title: 'Capture and dropout in single-cell sequencing', calc: 'capture',
    one: 'Zeros mix true absence with failed capture, inflating apparent heterogeneity.',
    form: 'Observed count ~ Binomial(<i>n</i>, <i>p</i><sub>cap</sub>) given true count <i>n</i>. P(zero) = (1 − <i>p</i><sub>cap</sub>)<sup><i>n</i></sup>. CV<sup>2</sup><sub>obs</sub> = CV<sup>2</sup><sub>true</sub> + (1 − <i>p</i><sub>cap</sub>)/(<i>p</i><sub>cap</sub> <i>n̄</i>).',
    assays: ['scRNA-seq', 'Single-cell ATAC and proteomics', 'Spatial transcriptomics'],
    effect: 'At 10 percent capture, a gene with five true transcripts is missed in 59 percent of cells, and technical noise dominates the apparent variance of all but the most abundant genes. Bimodality can be an artifact of capture.',
    diagnostic: 'Spike-in molecules of known abundance give the capture probability and the technical noise curve.',
    mitigation: 'Model dropout explicitly, pool cells for low-abundance genes, and compare only genes above the technical noise floor.',
    refs: [
      { t: 'Brennecke P, et al. Nat Methods 2013;10:1093–1095.', u: 'https://www.nature.com/articles/nmeth.2645' },
      { t: 'Kharchenko PV, Silberstein L, Scadden DT. Nat Methods 2014;11:740–742.', u: 'https://www.nature.com/articles/nmeth.2967' },
    ],
  },
  /* ------------------------------------------------------------------ C */
  {
    id: 'shot-noise', section: 'C', title: 'Photon shot noise and camera noise', calc: 'shot',
    one: 'Dim signals are noisier in proportion, so dim conditions fail thresholds more often.',
    form: 'Photons ~ Poisson(<i>N</i>); read noise ~ Normal(0, σ<sub>r</sub>). SNR = <i>N</i>/√(<i>N</i> + σ<sub>r</sub><sup>2</sup>). For sCMOS sensors σ<sub>r</sub> is pixel-specific. Localization precision scales as 1/√<i>N</i>.',
    assays: ['Fluorescence plate readers', 'Microscopy', 'Flow cytometry', 'Luminescence at low signal', 'Single-molecule localization'],
    effect: 'The variance of a dim signal scales with its mean, so a fixed intensity threshold misclassifies dim cells at a rate set by Poisson tails, and the misclassification is condition-dependent whenever the treatment changes brightness.',
    diagnostic: 'Plot variance against mean across a dilution series of a fluorescent standard; the slope is the gain and the intercept the read noise.',
    mitigation: 'Integrate longer or bin pixels, calibrate camera gain, and set thresholds from a noise model rather than a fixed value.',
    refs: [
      { t: 'Huang F, et al. Nat Methods 2013;10:653–658.', u: 'https://pubmed.ncbi.nlm.nih.gov/23708387/' },
    ],
    tool: { name: 'The Threshold Is Part of the Measurement', url: 'https://github.com/dataRichinsightPoor/threshold-is-part-of-the-measurement' },
  },
  {
    id: 'bleaching', section: 'C', title: 'Photobleaching and blinking', calc: 'bleach',
    one: 'Incomplete labeling turns subunit counts into a binomial, and the mode undercounts.',
    form: 'Observed steps ~ Binomial(<i>n</i>, <i>p</i><sub>label</sub>), with <i>p</i><sub>label</sub> the product of maturation, labeling and detection probabilities. Bleaching times are exponential; blinking adds re-appearances that inflate localization counts.',
    assays: ['Single-molecule step counting', 'Single-molecule localization microscopy', 'FRAP and long time-lapse imaging'],
    effect: 'For a tetramer with 75 percent effective labeling, the modal step count is three and only 32 percent of complexes show all four steps. Blinking produces repeated localizations of one molecule that are counted as clusters.',
    diagnostic: 'Count steps on a construct of known stoichiometry to estimate <i>p</i><sub>label</sub>; measure dark-state kinetics on sparse single molecules.',
    mitigation: 'Fit the full binomial mixture rather than reading the mode, and correct cluster counts with the measured blinking statistics.',
    refs: [
      { t: 'Ulbrich MH, Isacoff EY. Nat Methods 2007;4:319–321.', u: 'https://www.nature.com/articles/nmeth1024' },
    ],
  },
  {
    id: 'number-fluctuations', section: 'C', title: 'Number fluctuations in small volumes', calc: 'fcs',
    one: 'In a femtoliter at nanomolar concentration there is, on average, less than one molecule.',
    form: 'Molecules in the detection volume ~ Poisson(⟨<i>N</i>⟩), ⟨<i>N</i>⟩ = <i>c</i><i>V</i><i>N</i><sub>A</sub>. Relative variance 1/⟨<i>N</i>⟩, which is the amplitude <i>G</i>(0) in fluorescence correlation spectroscopy.',
    assays: ['Fluorescence correlation spectroscopy', 'Confocal and single-molecule detection', 'Nanowell and droplet readouts'],
    effect: 'At 1 nM in 1 fL, ⟨<i>N</i>⟩ ≈ 0.6, and intensity fluctuates by more than 100 percent from the mean. FCS uses this as signal; most other readouts treat it as noise.',
    diagnostic: 'The autocorrelation amplitude gives ⟨<i>N</i>⟩ directly; compare with the nominal concentration to detect adsorption or aggregation.',
    mitigation: 'Average over time or volume; for concentration measurements use the fluctuation amplitude rather than the mean intensity.',
    refs: [
      { t: 'Magde D, Elson E, Webb WW. Phys Rev Lett 1972;29:705–708.', u: 'https://profiles.wustl.edu/en/publications/thermodynamic-fluctuations-in-a-reacting-system-measurement-by-fl/' },
    ],
  },
  {
    id: 'berg-purcell', section: 'C', title: 'The physical limit of concentration sensing', calc: 'bp',
    one: 'A receptor patch cannot know a concentration better than the molecules that diffuse to it in the integration time.',
    form: 'A sphere of radius <i>a</i> in concentration <i>c</i> with diffusion coefficient <i>D</i> receives molecules at rate 4π<i>Dac</i>. A perfect absorber counting independent arrivals for time <i>T</i> has relative error 1/√(4π<i>DacT</i>); a perfectly monitoring sphere, which releases molecules and recounts their returns, has √(3/(5π<i>DacT</i>)), a variance 12/5 larger.',
    assays: ['Chemotaxis and gradient sensing', 'Receptor-occupancy readouts', 'Biosensor response time', 'Cell-based ligand titrations'],
    effect: 'At picomolar ligand, a micrometer-sized cell integrating for a minute sees too few independent molecular encounters for a precise response, so part of the cell-to-cell variability in response is a physical floor rather than biology.',
    diagnostic: 'Compare the measured response CV with the Berg–Purcell floor for the ligand concentration and exposure time.',
    mitigation: 'Lengthen exposure, raise concentration into the range where the floor is negligible, or model the floor explicitly.',
    refs: [
      { t: 'Berg HC, Purcell EM. Biophys J 1977;20:193–219.', u: 'https://pubmed.ncbi.nlm.nih.gov/911982/' },
    ],
  },
  {
    id: 'channel-gating', section: 'C', title: 'Stochastic ion channel gating', calc: 'channel',
    one: 'Macroscopic current fluctuates because each channel opens and closes at random.',
    form: 'Open channels ~ Binomial(<i>N</i>, <i>p</i><sub>o</sub>). Mean current <i>N</i><i>i</i><i>p</i><sub>o</sub>, variance <i>i</i><sup>2</sup><i>N</i><i>p</i><sub>o</sub>(1 − <i>p</i><sub>o</sub>), so variance is a parabola in the mean with apex at <i>p</i><sub>o</sub> = ½.',
    assays: ['Patch-clamp electrophysiology', 'Automated planar patch', 'Ion channel pharmacology'],
    effect: 'Non-stationary noise analysis recovers unitary current and channel number from the parabola; a drug that reduces current may lower <i>p</i><sub>o</sub>, <i>i</i> or <i>N</i>, which the mean alone cannot separate.',
    diagnostic: 'Plot ensemble variance against mean across the time course of a response.',
    mitigation: 'Fit the variance–mean relation; report <i>p</i><sub>o</sub>, <i>i</i> and <i>N</i> rather than peak current alone.',
    refs: [
      { t: 'Neher E, Sakmann B. Nature 1976;260:799–802.', u: 'https://www.nature.com/articles/260799a0' },
    ],
  },
  /* ------------------------------------------------------------------ D */
  {
    id: 'bursting', section: 'D', title: 'Transcriptional bursting and expression noise', calc: 'burst',
    one: 'A mean can double because more cells are on or because on cells are brighter, and the two imply different pharmacology.',
    form: 'Two-state telegraph model in the bursty limit: mRNA ~ NegBin with mean <i>f</i><i>b</i> and Fano factor 1 + <i>b</i>, where <i>f</i> is bursts per mRNA lifetime and <i>b</i> the burst size. Intrinsic and extrinsic noise separate with dual reporters.',
    assays: ['Reporter assays', 'Single-cell expression', 'Percent-positive readouts', 'smFISH'],
    effect: 'Percent positive depends on where the threshold sits in a skewed distribution. Doubling burst frequency and doubling burst size produce the same mean but different fractions above a threshold and different Fano factors.',
    diagnostic: 'Mean and variance together: the Fano factor estimates burst size; the mean divided by burst size gives frequency.',
    mitigation: 'Report distributions, not percent positive; fit frequency and size separately when a treatment shifts the mean.',
    refs: [
      { t: 'Elowitz MB, Levine AJ, Siggia ED, Swain PS. Science 2002;297:1183–1186.', u: 'https://pubmed.ncbi.nlm.nih.gov/12183631/' },
      { t: 'Raj A, van Oudenaarden A. Cell 2008;135:216–226.', u: 'https://pubmed.ncbi.nlm.nih.gov/18957198/' },
      { t: 'Lenstra TL, Rodriguez J, Chen H, Larson DR. Annu Rev Biophys 2016;45:25–47.', u: 'https://pubmed.ncbi.nlm.nih.gov/27145880/' },
    ],
  },
  {
    id: 'protein-memory', section: 'D', title: 'Variability and memory of protein levels', calc: 'sort',
    one: 'A sorted high population relaxes toward the parent, and the relaxation mimics an induced effect.',
    form: 'Log protein level as an Ornstein–Uhlenbeck process with mixing time τ. After sorting the top fraction <i>q</i>, the mean excess decays as e<sup>−<i>t</i>/τ</sup> and the variance returns as 1 − e<sup>−2<i>t</i>/τ</sup>. Memory lasting more than two generations has been measured in human cells.',
    assays: ['Sort-then-assay experiments', 'Drug response after enrichment', 'Time-course imaging', 'Reporter stability'],
    effect: 'A population sorted for high expression is enriched by about two standard deviations immediately and by a fraction e<sup>−<i>t</i>/τ</sup> of that later. Measuring the sorted population at different times after sorting yields different answers for reasons unrelated to treatment.',
    diagnostic: 'Re-measure the sorted population at several times without treatment; the decay gives τ.',
    mitigation: 'Fix the interval between sort and assay, include a mock-sorted control, and compare against the relaxation curve.',
    refs: [
      { t: 'Sigal A, et al. Nature 2006;444:643–646.', u: 'https://pubmed.ncbi.nlm.nih.gov/17122776/' },
      { t: 'Cohen AA, et al. Science 2008;322:1511–1516.', u: 'https://pubmed.ncbi.nlm.nih.gov/19023046/' },
    ],
  },
  {
    id: 'fractional-killing', section: 'D', title: 'Fractional killing and survivor enrichment', calc: 'kill',
    one: 'Survivors are not resistant; they are sampled from the protected tail of a state distribution, and the state persists.',
    form: 'A protective state <i>x</i> = exp(σ<i>Z</i>) with <i>Z</i> ~ Normal(0, 1). A cell survives dose <i>D</i> if <i>Z</i> > <i>z</i><sub>c</sub> = ln(<i>D</i>/<i>D</i><sub>50</sub>)/σ, so survival is 1 − Φ(<i>z</i><sub>c</sub>). With correlation ρ between the state at two doses, survival of the second dose among first-dose survivors is [1 − 2Φ(<i>z</i><sub>c</sub>) + Φ<sub>2</sub>(<i>z</i><sub>c</sub>, <i>z</i><sub>c</sub>; ρ)]/[1 − Φ(<i>z</i><sub>c</sub>)].',
    assays: ['Cytotoxicity and apoptosis assays', 'Dose–response plateaus', 'Repeat-dose and washout experiments', 'Drug-tolerant persister studies'],
    effect: 'Dose–response curves plateau below complete killing for non-genetic reasons. With ρ = 0.8, a second identical dose kills about half as large a fraction as the first, which looks like acquired resistance and is instead enrichment plus memory.',
    diagnostic: 'Re-dose survivors after increasing recovery intervals; killing returns toward the first-dose value as the state re-randomizes.',
    mitigation: 'Report Emax with its plateau, model survival as a state distribution, and separate enrichment from heritable resistance by the recovery time course.',
    refs: [
      { t: 'Spencer SL, Gaudet S, Albeck JG, Burke JM, Sorger PK. Nature 2009;459:428–432.', u: 'https://pubmed.ncbi.nlm.nih.gov/19363473/' },
      { t: 'Shaffer SM, et al. Nature 2017;546:431–435.', u: 'https://pubmed.ncbi.nlm.nih.gov/28607484/' },
    ],
  },
  {
    id: 'persisters', section: 'D', title: 'Phenotypic switching and persisters', calc: 'persist',
    one: 'Kill curves are biphasic because a pre-existing subpopulation dies slowly.',
    form: 'Surviving fraction (1 − <i>f</i>)e<sup>−<i>k</i><sub>s</sub><i>t</i></sup> + <i>f</i>e<sup>−<i>k</i><sub>p</sub><i>t</i></sup>, with persister fraction <i>f</i> set by switching rates before exposure. Time to 99.9 percent kill is dominated by the slow phase once (1 − <i>f</i>)e<sup>−<i>k</i><sub>s</sub><i>t</i></sup> falls below <i>f</i>.',
    assays: ['Antibiotic time-kill and MIC assays', 'Cancer drug-tolerance assays', 'Antiviral and antiparasitic kill kinetics'],
    effect: 'Endpoint assays read the switching equilibrium, not the drug. With <i>f</i> = 0.1 percent and a slow-phase rate of 0.01 per hour, time to 99.9 percent kill is set by the persisters regardless of how fast the main population dies. Results depend on growth phase and inoculum history.',
    diagnostic: 'Sample the kill curve densely enough to see the inflection; regrow survivors and re-expose to show they are not resistant mutants.',
    mitigation: 'Report both phases and the persister fraction; standardize culture history before exposure.',
    refs: [
      { t: 'Balaban NQ, Merrin J, Chait R, Kowalik L, Leibler S. Science 2004;305:1622–1625.', u: 'https://pubmed.ncbi.nlm.nih.gov/15308767/' },
    ],
  },
  {
    id: 'switching', section: 'D', title: 'Epigenetic switching, silencing and monoallelic expression', calc: 'switch',
    one: 'A pool of cells drifts toward its switching equilibrium, and each clone has made its own random choices.',
    form: 'Two-state Markov chain with silencing rate <i>k</i><sub>off</sub> and reactivation rate <i>k</i><sub>on</sub> per generation. Fraction expressing <i>p</i>(<i>t</i>) = <i>p</i><sub>eq</sub> + (<i>p</i><sub>0</sub> − <i>p</i><sub>eq</sub>)e<sup>−(<i>k</i><sub>on</sub>+<i>k</i><sub>off</sub>)<i>t</i></sup>, <i>p</i><sub>eq</sub> = <i>k</i><sub>on</sub>/(<i>k</i><sub>on</sub> + <i>k</i><sub>off</sub>). Random monoallelic choice is a one-time switch inherited by the clone.',
    assays: ['Stable reporter and producer lines', 'Transgene expression over passages', 'Clonal cell lines', 'Allele-specific assays'],
    effect: 'Pools drift toward low expressers at a rate that depends on integration site. Clones from one parent differ in which allele they express, so a heterozygous variant can appear absent or dominant depending on the clone. Silencing is stochastic and all-or-none per cell rather than a graded dimming.',
    diagnostic: 'Follow the expressing fraction over passages; bimodal single-cell distributions indicate switching rather than graded loss.',
    mitigation: 'Use insulated or targeted integration, bank early passages, and report the expressing fraction and its trajectory.',
    refs: [
      { t: 'Bintu L, et al. Science 2016;351:720–724.', u: 'https://pubmed.ncbi.nlm.nih.gov/26912859/' },
      { t: 'Gimelbrant A, Hutchinson JN, Thompson BR, Chess A. Science 2007;318:1136–1140.', u: 'https://pubmed.ncbi.nlm.nih.gov/18006746/' },
    ],
  },
  {
    id: 'growth-variability', section: 'D', title: 'Growth and cell-cycle stochasticity', calc: 'clone',
    one: 'Identical genotypes give broad clone-size distributions because division times vary.',
    form: 'Divisions in a fixed time ~ Normal(<i>n̄</i>, <i>n̄</i>·CV<sub>T</sub><sup>2</sup>) by the renewal theorem, so clone size is approximately lognormal with σ<sub>ln</sub> = ln 2 · CV<sub>T</sub>√<i>n̄</i>. Expression fluctuations in metabolic enzymes propagate into growth-rate fluctuations.',
    assays: ['Proliferation endpoints', 'Colony-size assays', 'Outgrowth after single-cell deposition', 'Phase-specific drug responses'],
    effect: 'With 20 percent division-time CV over ten divisions, the 90th-percentile clone is about 3.2 times the size of the 10th percentile. Endpoint counts mix growth rate with lag-time variability, and asynchronous cycle phase makes phase-specific drugs act on a random fraction.',
    diagnostic: 'Clone-size distributions on a log scale; time-lapse division intervals.',
    mitigation: 'Use growth rate rather than endpoint count, and enough clones to average the lognormal tail.',
    refs: [
      { t: 'Kiviet DJ, et al. Nature 2014;514:376–379.', u: 'https://www.nature.com/articles/nature13582' },
    ],
  },
  /* ------------------------------------------------------------------ E */
  {
    id: 'luria-delbruck', section: 'E', title: 'Mutation timing and jackpots', calc: 'ld',
    one: 'Mutants that arise early in an expansion dominate the count, so the mean misleads and the zero class informs.',
    form: 'Mutations occur at rate μ per division during expansion to <i>N</i> cells; expected mutations <i>m</i> = μ<i>N</i>. The Lea–Coulson distribution of mutant counts has P(0) = e<sup>−<i>m</i></sup> and a heavy right tail, computed by the recursion <i>p</i><sub><i>r</i></sub> = (<i>m</i>/<i>r</i>) Σ<sub><i>i</i>&lt;<i>r</i></sub> <i>p</i><sub><i>i</i></sub>/(<i>r</i> − <i>i</i> + 1).',
    assays: ['Fluctuation tests', 'Resistance frequency', 'Escape-mutant emergence', 'Mutagenesis assays'],
    effect: 'Replicate cultures with the same <i>m</i> show mutant counts ranging over orders of magnitude. The arithmetic mean has no finite expectation in the idealized model; the variance between cultures carries the information. A resistance frequency measured from one or two flasks is mostly a measurement of when the first mutation happened.',
    diagnostic: 'Compare the between-culture variance with Poisson; a ratio far above one is the Luria–Delbrück signature.',
    mitigation: 'Use many parallel cultures, estimate <i>m</i> from the zero class or by maximum likelihood, and report the mutation rate rather than a frequency.',
    refs: [
      { t: 'Luria SE, Delbrück M. Genetics 1943;28:491–511.', u: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC1209226/' },
    ],
  },
  {
    id: 'clonal-drift', section: 'E', title: 'Clonal drift and evolution of cell lines', calc: 'drift',
    one: 'The same cell line is a population whose composition is a random walk with selection.',
    form: 'Subclone frequency <i>p</i> changes by selection <i>p</i>′ = <i>p</i>e<sup><i>s</i></sup>/(<i>p</i>e<sup><i>s</i></sup> + 1 − <i>p</i>) and by drift with variance <i>p</i>′(1 − <i>p</i>′)/<i>N</i> per passage, where <i>N</i> is the effective number of cells carried forward.',
    assays: ['Any cell-based assay compared across passages or laboratories', 'Drug sensitivity panels', 'Engineered producer lines'],
    effect: 'Twenty-seven strains of one breast cancer line differed in response to most of 321 compounds. Within-laboratory replication cannot reveal this because the replicates share the same population. Clonal origin certifies nothing about later composition.',
    diagnostic: 'Barcode or SNP-track subclone frequencies across passages; compare early and late banks on the same assay.',
    mitigation: 'Bank early, limit passage number, and treat strain identity as a covariate when comparing across sites.',
    refs: [
      { t: 'Ben-David U, et al. Nature 2018;560:325–330.', u: 'https://www.nature.com/articles/s41586-018-0409-3' },
      { t: 'Vcelar S, et al. Biotechnol Bioeng 2018;115:165–173.', u: 'https://doi.org/10.1002/bit.26453' },
    ],
  },
  {
    id: 'mt-bottleneck', section: 'E', title: 'Mitochondrial heteroplasmy segregation', calc: 'mt',
    one: 'A bottleneck in mtDNA copy number turns a stable heteroplasmy into a spread of genotypes.',
    form: 'Heteroplasmy after a bottleneck of <i>n</i> segregating units has variance <i>h</i>(1 − <i>h</i>)/<i>n</i>; over <i>g</i> generations of drift, <i>h</i>(1 − <i>h</i>)(1 − (1 − 1/<i>n</i>)<sup><i>g</i></sup>).',
    assays: ['Cybrid and mitochondrial disease models', 'Heteroplasmy assays in single cells and clones', 'Mitochondrial toxicity assays'],
    effect: 'Clones derived from one heteroplasmic parent differ in mutant load, and threshold phenotypes appear in a random subset. Assays on clonal lines sample one draw from the segregation distribution.',
    diagnostic: 'Measure heteroplasmy in many single cells or clones; the variance gives the effective bottleneck size.',
    mitigation: 'Characterize heteroplasmy per clone, and use several clones per genotype.',
    refs: [
      { t: 'Cree LM, et al. Nat Genet 2008;40:249–254.', u: 'https://www.nature.com/articles/ng.2007.63' },
    ],
  },
  {
    id: 'initiating-frequency', section: 'E', title: 'Initiating-cell frequency by limiting-dilution transplantation', calc: 'elda',
    one: 'Take rates across doses estimate a frequency whose interval spans several fold unless the design brackets it.',
    form: 'Single-hit Poisson: P(take at dose <i>x</i>) = 1 − e<sup>−<i>x</i><i>f</i></sup>. Fisher information for ln <i>f</i> is Σ <i>n</i><sub><i>i</i></sub>(<i>x</i><sub><i>i</i></sub><i>f</i>)<sup>2</sup>e<sup>−<i>x</i><sub><i>i</i></sub><i>f</i></sup>/(1 − e<sup>−<i>x</i><sub><i>i</i></sub><i>f</i></sup>), and the standard error of ln <i>f</i> is its inverse square root.',
    assays: ['Tumor-initiating cell assays', 'Stem cell repopulation', 'HIV latent reservoir quantification', 'Organoid-forming efficiency'],
    effect: 'With four doses of six animals each bracketing a frequency of 1 in 1,000, the 95 percent interval spans about fourfold. Doses that all take or all fail contribute no information. Differences below threefold between populations are rarely resolvable.',
    diagnostic: 'Check that doses span the transition from mostly negative to mostly positive, and test the single-hit assumption with a goodness-of-fit statistic.',
    mitigation: 'Place doses geometrically around the expected frequency and use the ELDA likelihood with its interval.',
    refs: [
      { t: 'Hu Y, Smyth GK. J Immunol Methods 2009;347:70–78.', u: 'https://pubmed.ncbi.nlm.nih.gov/19567251/' },
    ],
  },
  /* ------------------------------------------------------------------ F */
  {
    id: 'hierarchy', section: 'F', title: 'Replicate hierarchy and hidden covariates', calc: 'hier',
    one: 'Wells within a plate are not independent samples of the condition, and the naive standard error says they are.',
    form: 'Var(condition mean) = σ<sub>day</sub><sup>2</sup>/<i>n</i><sub>d</sub> + σ<sub>plate</sub><sup>2</sup>/(<i>n</i><sub>d</sub><i>n</i><sub>p</sub>) + σ<sub>well</sub><sup>2</sup>/(<i>n</i><sub>d</sub><i>n</i><sub>p</sub><i>n</i><sub>w</sub>). Pooling all wells as independent divides the total variance by the total count and understates the error.',
    assays: ['Every plate-based assay', 'Imaging screens', 'Animal studies with cage effects'],
    effect: 'With day, plate and well standard deviations of 0.15, 0.10 and 0.10 on a log scale, 48 wells across 2 plates and 3 days give a true standard error 3.3 times the naive one. Population context, including local density and position in the colony, explains much of what is called cell-to-cell variability.',
    diagnostic: 'Variance-component analysis on controls; plate-position heat maps; the correlation between neighboring wells.',
    mitigation: 'Randomize positions, replicate at the level where variance lives, and analyze with mixed models.',
    refs: [
      { t: 'Snijder B, et al. Nature 2009;461:520–523.', u: 'https://pelkmanslab.org/wp-content/uploads/2019/02/Snijder2009.pdf' },
    ],
  },
  /* ------------------------------------------------------------------ G */
  {
    id: 'spheroid-hook', section: 'G', title: 'The hooked penetration curve', calc: 'hook',
    one: 'Running out of secondary gives a plateau. A genuine fall needs carryover, crowding or self-quenching, and each has a different shape.',
    form: 'Primary front depth <i>L</i> = min(<i>R</i>, √(2<i>D</i><i>t</i><i>C</i><sub>0</sub>/<i>B</i><sub>T</sub>)) in the binding-site-barrier regime, occupancy θ = <i>C</i><sub>0</sub>/(<i>C</i><sub>0</sub> + <i>K</i><sub>d</sub>). Secondaries per primary <i>n</i><sub>s</sub> = <i>n</i><sub>max</sub>(1 − γθ) (crowding). Dye density ρ = <i>B</i><sub>T</sub>θ<i>n</i><sub>s</sub>·DOL; brightness per dye e<sup>−ρ/ρ<sub>q</sub></sup> (self-quenching). Whole-mount signal at depth <i>z</i> is attenuated by e<sup>−(μ + ερ)<i>z</i></sup>. Secondary front <i>L</i><sub>s</sub> = √(2<i>D</i><i>t</i><sub>s</sub><i>C</i><sub>s,eff</sub>/(<i>B</i><sub>T</sub>θ<i>n</i><sub>s</sub>)) with <i>C</i><sub>s,eff</sub> = <i>C</i><sub>s</sub> − <i>n</i><sub>s</sub>·carryover·<i>C</i><sub>0</sub>.',
    assays: ['Spheroid and organoid antibody penetration', 'Whole-mount immunofluorescence', 'Tissue-section titrations', 'Antibody–drug conjugate distribution models'],
    effect: 'A fixed secondary concentration caps the detected depth and produces a plateau, not a hook. Free primary carried into the secondary step sequesters secondary and drives the signal to zero at high concentration. Crowding and self-quenching dim the rim first, so the rim is darker than a partially stained interior. Attenuation keeps the rim bright and dims the interior. A directly labeled primary is monotonic under all four.',
    diagnostic: 'Titrate the secondary at fixed primary; add washes; compare sections with whole mounts; run a directly labeled primary at the same concentrations; measure rim and 100 µm intensities separately.',
    mitigation: 'Use the secondary in large excess or a direct label, report penetration in micrometers against the spheroid radius distribution, and measure the curve rather than one dose.',
    refs: [
      { t: 'Fujimori K, Covell DG, Fletcher JE, Weinstein JN. J Nucl Med 1990;31:1191–1198.', u: 'https://pubmed.ncbi.nlm.nih.gov/2362198/' },
      { t: 'Thurber GM, Schmidt MM, Wittrup KD. Adv Drug Deliv Rev 2008;60:1421–1434.', u: 'https://pubmed.ncbi.nlm.nih.gov/18541331/' },
      { t: 'Tate J, Ward G. Clin Biochem Rev 2004;25:105–120.', u: 'https://pubmed.ncbi.nlm.nih.gov/18458713/' },
      { t: 'Minchinton AI, Tannock IF. Nat Rev Cancer 2006;6:583–592.', u: 'https://www.nature.com/articles/nrc1893' },
      { t: 'Nürnberg E, et al. Front Mol Biosci 2020;7:20.', u: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7046628/' },
    ],
  },
  {
    id: 'wicksell', section: 'G', title: 'The random section plane', calc: 'wicksell',
    one: 'A cryosection cuts the sphere at a random height, and off-equator sections overstate the stained shell.',
    form: 'Section offset <i>z</i> ~ Uniform(0, <i>R</i>). Apparent radius √(<i>R</i><sup>2</sup> − <i>z</i><sup>2</sup>), mean π<i>R</i>/4. A shell of true thickness <i>t</i> appears as √(<i>R</i><sup>2</sup> − <i>z</i><sup>2</sup>) − √((<i>R</i> − <i>t</i>)<sup>2</sup> − <i>z</i><sup>2</sup>), and sections with <i>z</i> > <i>R</i> − <i>t</i>, a fraction <i>t</i>/<i>R</i>, look fully stained.',
    assays: ['Spheroid and organoid cryosections', 'Tumor histology', 'Any stereology of shells around spheres'],
    effect: 'For a 250 µm spheroid with a 50 µm stained shell, the mean apparent shell is about 71 µm, a 41 percent overstatement, and one section in five appears fully penetrated. Choosing the largest section from a series removes most of the bias but selects on staining quality at the same time.',
    diagnostic: 'Plot apparent shell thickness against apparent section radius; the Wicksell relation predicts the curve.',
    mitigation: 'Section serially and use the equatorial section, or image whole mounts and measure depth in three dimensions.',
    refs: [
      { t: 'Wicksell SD. Biometrika 1925;17:84–99.', u: 'https://doi.org/10.1093/biomet/17.1-2.84' },
    ],
  },
  {
    id: 'spheroid-size', section: 'G', title: 'Spheroid size from Poisson seeding', calc: 'seed',
    one: 'The cell count per drop is a Poisson draw, and the radius inherits a third of its coefficient of variation.',
    form: 'Cells per drop ~ Poisson(<i>n̄</i>) with extra dispensing variance CV<sub>x</sub>. CV of count √(1/<i>n̄</i> + CV<sub>x</sub><sup>2</sup>); radius ∝ count<sup>1/3</sup>, so CV<sub>R</sub> ≈ CV<sub>count</sub>/3.',
    assays: ['Hanging-drop and ultra-low-attachment spheroids', 'Organoid formation', 'Any readout normalized to spheroid volume'],
    effect: 'Penetration depth in micrometers is independent of size only in the planar limit; the core-to-rim ratio is not, because a larger spheroid has more core. A dose that saturates a 300 µm spheroid leaves a 500 µm spheroid hollow, so the hook position depends on the size distribution of the replicates.',
    diagnostic: 'Measure the radius distribution before staining; regress penetration metrics on radius.',
    mitigation: 'Report penetration in absolute micrometers with the radius distribution, or size-match spheroids before treatment.',
    refs: [
      { t: 'Size polydispersity from stochastic seeding in multicellular aggregates (PMC).', u: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11884609/' },
    ],
  },
];

export const ASSAYS = [...new Set(ENTRIES.flatMap(e => e.assays))].sort();
